/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.MecanicoMenu;

import sistemaoficina.Funcionarios.Administrador;
import sistemaoficina.Funcionarios.Mecanico;
import sistemaoficina.Funcionarios.Vendedor;
import telas.Login;

/**
 *
 * @author maceg
 */
public class MenuMecanico extends javax.swing.JDialog {
    //Variavel login para receber o ponteiro da tela login   
    private Login login;
    //Variavel mecanico para receber o ponteiro da variavel mecanico original e permitir a atualizacao de seus campos
    private Mecanico mecani;
    private Vendedor vende;
    private Administrador adm;
    /**
     * Creates new form MecanicoMenu
     */
    //Construtor basico criado pelo NetBeans
    public MenuMecanico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    //Construtos basico que nao necessita de parametros e inicializa os componentes da tela
    public MenuMecanico() {
    
        initComponents();
    }
    //Construtor que chama o construtor anterior e recebe os dados da tela anterior
    public MenuMecanico(Login login, Mecanico mecani, Vendedor vendedor, Administrador adm) {
        this();
        this.login = login;
        this.mecani = mecani;
        this.vende = vendedor;
        this.adm = adm;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listarOrdems = new javax.swing.JButton();
        cadastraServicos = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Mecânico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        listarOrdems.setText("Visualizar ordems de serviço abertas");
        listarOrdems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarOrdemsActionPerformed(evt);
            }
        });

        cadastraServicos.setText("Cadastrar serviços executados");
        cadastraServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraServicosActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU MECÂNICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listarOrdems, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(cadastraServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(listarOrdems)
                .addGap(33, 33, 33)
                .addComponent(cadastraServicos)
                .addGap(32, 32, 32)
                .addComponent(botaoSair)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Botao que leve a tela ListarOrdems
    private void listarOrdemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarOrdemsActionPerformed
        // TODO add your handling code here:
        //Tornando a tela atual invisivel de forma deixar mais "limpa" a apresentacao das telas
        this.setVisible(false);
        //Chamando o construtor da tela ListarOrdems e tornando-a visivel, esta sendo passado a variavel mecanico, para permitir a troca  dados entre telas
        new ListarOrdems(this, this.mecani, this.vende).setVisible(true);
        
    }//GEN-LAST:event_listarOrdemsActionPerformed
    //Botao que leva a tela EditarOrdem
    private void cadastraServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraServicosActionPerformed
        // TODO add your handling code here:
        //Tornando a tela atual invisivel de forma deixar mais "limpa" a apresentacao das telas
        this.setVisible(false);
        //Chamando o construtor da tela EditarOrdem e tornando-a visivel
        new EditarOrdem(this, this.mecani).setVisible(true);
    }//GEN-LAST:event_cadastraServicosActionPerformed
    //Funcao para quando a tela for fechada
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //Tornando a tela anterior visivel novamente, possivel visto que ela foi passada no construtor
        if(mecani.getOrdem() != null){
            adm.setMecanico(mecani);
        }
        login.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosed
    //Botao sai
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        //Torna a tela atual invisivel de forma a simular o fechamento dessa
        this.setVisible(false);
        
        if(mecani.getOrdem() != null){
            adm.setMecanico(mecani);
        } 
        
        //Torna a tela anterior visivel novamente
        login.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuMecanico dialog = new MenuMecanico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton cadastraServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listarOrdems;
    // End of variables declaration//GEN-END:variables
}
