/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.VendedorMenu;

import telas.Login;
import sistemaoficina.Funcionarios.Vendedor;

/**
 *
 * @author marcus
 */
public class MenuVendedor extends javax.swing.JFrame {
    
    private Login login;
    private Vendedor vendedor;
    private CadastroClienteCarro cadastroCliCa;
    private CadastroOrdem cadastroOrd;
    private VisualizarClientes visualizarCli;
    private VisualizarOrdensPendentes visualizarOrdPen;
    private VisualizarOrdensConcluidas visualizarOrdCon;
    /**
     * Creates new form MenuVendedor
     */
    
    public MenuVendedor() {
        initComponents();
    }
    
    /**
    * Responsavel por enviar as referencias de login e vendedor para a tela MenuVendedor
    * @param login - Tela Login
    * @param vendedor - Variavel a ser passada
    */
    public void enviaVendedorLogin(Login login, Vendedor vendedor) {
        this.login = login;
        this.vendedor = vendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CadastroClienteCarro = new javax.swing.JButton();
        GerarOrdem = new javax.swing.JButton();
        VisualizarClientes = new javax.swing.JButton();
        VisualizarOrdensPendentes = new javax.swing.JButton();
        VisualizarOrdensExecutadas = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Vendedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("MENU VENDEDOR");

        CadastroClienteCarro.setText("Cadastrar cliente e carro");
        CadastroClienteCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteCarroActionPerformed(evt);
            }
        });

        GerarOrdem.setText("Gerar ordem de serviço");
        GerarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarOrdemActionPerformed(evt);
            }
        });

        VisualizarClientes.setText("Visualizar clientes");
        VisualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarClientesActionPerformed(evt);
            }
        });

        VisualizarOrdensPendentes.setText("Visualizar ordens de serviços pendentes");
        VisualizarOrdensPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarOrdensPendentesActionPerformed(evt);
            }
        });

        VisualizarOrdensExecutadas.setText("Visualizar ordens de serviços executados");
        VisualizarOrdensExecutadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarOrdensExecutadasActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadastroClienteCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GerarOrdem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VisualizarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VisualizarOrdensPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VisualizarOrdensExecutadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(CadastroClienteCarro)
                .addGap(13, 13, 13)
                .addComponent(GerarOrdem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisualizarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisualizarOrdensPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisualizarOrdensExecutadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Aloca a tela de Cadastro de cliente e carro, mantendo a referencia a tela 
    * atual e deixando ela fora de visão
    */
    private void CadastroClienteCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteCarroActionPerformed
        cadastroCliCa = new CadastroClienteCarro();
        cadastroCliCa.setLocationRelativeTo(null);
        cadastroCliCa.setVisible(true);
        cadastroCliCa.setResizable(false);
        this.setVisible(false);
        
        cadastroCliCa.enviaVendedor(this, vendedor);
    }//GEN-LAST:event_CadastroClienteCarroActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
    * Aloca a tela de Visualizar clientes, mantendo a referencia a tela 
    * atual e deixando ela fora de visão
    */
    private void VisualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarClientesActionPerformed
        visualizarCli = new VisualizarClientes();
        visualizarCli.setLocationRelativeTo(null);
        visualizarCli.setVisible(true);
        visualizarCli.setResizable(false);
        this.setVisible(false);  
        
        visualizarCli.enviaVendedor(this, vendedor);
    }//GEN-LAST:event_VisualizarClientesActionPerformed

    /**
    * Aloca a tela de Gerar ordens, mantendo a referencia a tela 
    * atual e deixando ela fora de visão
    */
    private void GerarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarOrdemActionPerformed
        cadastroOrd = new CadastroOrdem();
        cadastroOrd.setLocationRelativeTo(null);
        cadastroOrd.setVisible(true);
        cadastroOrd.setResizable(false);
        this.setVisible(false);   
        
        cadastroOrd.enviaVendedor(this, vendedor);
    }//GEN-LAST:event_GerarOrdemActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.setVisible(false);
        login.setVendedorLogin(vendedor);
        login.setVisible(true);
    }//GEN-LAST:event_SairActionPerformed

    /**
    * Aloca a tela de Visualizar as ordens pendentes, mantendo a referencia a tela 
    * atual e deixando ela fora de visão
    */
    private void VisualizarOrdensPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarOrdensPendentesActionPerformed
        visualizarOrdPen = new VisualizarOrdensPendentes();
        visualizarOrdPen.setLocationRelativeTo(null);
        visualizarOrdPen.setVisible(true);
        visualizarOrdPen.setResizable(false);
        this.setVisible(false);   
        
        visualizarOrdPen.enviaVendedor(this, vendedor);
    }//GEN-LAST:event_VisualizarOrdensPendentesActionPerformed

    /**
    * Aloca a tela de Visualizar ordens concluidas, mantendo a referencia a tela 
    * atual e deixando ela fora de visão
    */
    private void VisualizarOrdensExecutadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarOrdensExecutadasActionPerformed
        visualizarOrdCon = new VisualizarOrdensConcluidas();
        visualizarOrdCon.setLocationRelativeTo(null);
        visualizarOrdCon.setVisible(true);
        visualizarOrdCon.setResizable(false);
        this.setVisible(false);   
        
        visualizarOrdCon.enviaVendedor(this, vendedor);
    }//GEN-LAST:event_VisualizarOrdensExecutadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVendedor().setVisible(true);
            }
        });
    }
    
    protected Vendedor getVendedor() {
        return vendedor;
    }
    
    protected void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroClienteCarro;
    private javax.swing.JButton GerarOrdem;
    private javax.swing.JButton Sair;
    private javax.swing.JButton VisualizarClientes;
    private javax.swing.JButton VisualizarOrdensExecutadas;
    private javax.swing.JButton VisualizarOrdensPendentes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
