/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.MecanicoMenu;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sistemaoficina.Funcionarios.Mecanico;

/**
 *
 * @author maceg
 */
public class EditarOrdem extends javax.swing.JDialog {
    //Variavel MenuMecanico para receber o endereco de memoria da tela anterior e permitir a edicao de certos dados
    private MenuMecanico menu_mecanico;
    //Variavel Mecanico para receber o endereco de memoria da tela anterior e permitr a edicao de certos dados, bem como mante-los salvos 
    private Mecanico mecani;
    /**
     * Creates new form EditarOrdem
     */
    //Construtor padrao do NetBeans
    public EditarOrdem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    //Construtor basico que apenas inicializa os componentes da tela
    public EditarOrdem() {
    
        initComponents();
    }
    //Construtor que recebe difentes parametros para settar os objetos da tela
    public EditarOrdem(MenuMecanico menu_mecanico, Mecanico mecani) {
        //Chamando o construtor basico
        this();
        //Menu Mecanico esta recebendo o endereco de memoria da tela anterior
        this.menu_mecanico = menu_mecanico; 
        //Mecanico recebendo o endereco do mecanico, de forma a inicializa-lo e manter as atualizacoes quando essa tela for fechada
        this.mecani = mecani;
          
    
    }
    public boolean verificaCampoInt(JTextField text){
        int aux;
        try{
            aux = Integer.parseInt(text.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Campo invalido", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        confirmServico = new javax.swing.JButton();
        inputServico = new javax.swing.JTextField();
        botaoSairEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição Ordem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Número de serviços: ");

        confirmServico.setText("Confirmar");
        confirmServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmServicoActionPerformed(evt);
            }
        });

        botaoSairEdit.setText("Sair");
        botaoSairEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairEditActionPerformed(evt);
            }
        });

        jLabel2.setText("EDIÇÃO ORDEM");

        jLabel3.setText("1-Utilize apenas números");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputServico))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoSairEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(confirmServico, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmServico)
                    .addComponent(botaoSairEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Botao para confirmar o recebimento de um servico e abrir a proxima tela
    private void confirmServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmServicoActionPerformed
        // TODO add your handling code here:
        //Torna a tela atual invisivel de forma a "limpar" a tela
        if(verificaCampoInt(inputServico) == true){
            this.setVisible(false);
            
            //Chama o construtor de FormatarServicos e torna a tela visivel, esta sendo passado o input do campo de texto, no entanto ele esta sendo convertido para int
            new FormatarServicos(this, Integer.parseInt(inputServico.getText()), this.mecani).setVisible(true);
        }
    }//GEN-LAST:event_confirmServicoActionPerformed
    
    //Acao para quando a tela for fechada
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //Torna a tela anterior visivel
        menu_mecanico.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void botaoSairEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairEditActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu_mecanico.setVisible(true);
    }//GEN-LAST:event_botaoSairEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarOrdem dialog = new EditarOrdem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSairEdit;
    private javax.swing.JButton confirmServico;
    private javax.swing.JTextField inputServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
