/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.AdmMenu;

import javax.swing.JLabel;
import sistemaoficina.Funcionarios.Administrador;
import sistemaoficina.Funcionarios.Mecanico;

/**
 *
 * @author marcu
 */
public class VisualizarMecanico extends javax.swing.JFrame {
    
    private int space = 40;
    private SelecionarMecanico selec;
    
    private int idMeca;
    private Mecanico mecanicoX;
      
    private Administrador adm;
    
    //Listar informações de um mecânico em forma de lista dinâmica
    public void showMecanicos(){
        
        mecanicoX = adm.getMecanico(idMeca);
        
        JLabel labelNome = new javax.swing.JLabel();        
        labelNome.setVisible(true);
        labelNome.setText("Nome:  " + mecanicoX.getNome());
        labelNome.setSize(300,40);
        labelNome.setLocation(50, space);
        getContentPane().add(labelNome);
        
        
        space+=20;
        JLabel labelCpf = new javax.swing.JLabel();   
        labelCpf.setVisible(true);
        labelCpf.setText("Cpf:  " + mecanicoX.getCpf());
        labelCpf.setSize(300,40);
        labelCpf.setLocation(50, space);
        getContentPane().add(labelCpf);
        
        space+=20;
        JLabel labelRg = new javax.swing.JLabel(); 
        labelRg.setVisible(true);
        labelRg.setText("Rg:  " + mecanicoX.getRg());
        labelRg.setSize(300,40);
        labelRg.setLocation(50, space);
        getContentPane().add(labelRg);
        
        space+=20;
        JLabel labelEndereco = new javax.swing.JLabel(); 
        labelEndereco.setVisible(true);
        labelEndereco.setText("Endereco:  " + mecanicoX.getEndereco());
        labelEndereco.setSize(300,40);
        labelEndereco.setLocation(50, space);
        getContentPane().add(labelEndereco);
        
        space+=20;
        JLabel labelTelefone = new javax.swing.JLabel(); 
        labelTelefone.setVisible(true);
        labelTelefone.setText("Telefone:  " + mecanicoX.getTelefone());
        labelTelefone.setSize(300,40);
        labelTelefone.setLocation(50, space);
        getContentPane().add(labelTelefone);
        
        space+=20;
        JLabel labelEmail = new javax.swing.JLabel(); 
        labelEmail.setVisible(true);
        labelEmail.setText("Email:  " + mecanicoX.getEmail());
        labelEmail.setSize(300,40);
        labelEmail.setLocation(50, space);
        getContentPane().add(labelEmail);
                
        initComponents();
    }

    /**
     * Creates new form SelecionarVendedor
     */
    public VisualizarMecanico() {
        initComponents();
    }
    
    public VisualizarMecanico(SelecionarMecanico selec) {
        this();
        this.selec = selec;
    }
    
    public void enviaCadastroLogin(SelecionarMecanico selec, Administrador adm, int id) {
        this.selec = selec;
        this.adm = adm;
        idMeca = id;
        showMecanicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Mecânico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("DADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Voltar)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Voltar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.setVisible(false);
        selec.recebeAdm(adm);        
        selec.setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        selec.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarMecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
